// var colorNames = [
//     "AliceBlue",
//     "AntiqueWhite",
//     "Aqua",
//     "Aquamarine",
//     "Azure",
//     "Beige",
//     "Bisque",
//     "Black",
//     "BlanchedAlmond",
//     "Blue",
//     "BlueViolet",
//     "Brown",
//     "BurlyWood",
//     "CadetBlue",
//     "Chartreuse",
//     "Chocolate",
//     "Coral",
//     "CornflowerBlue",
//     "Cornsilk",
//     "Crimson",
//     "Cyan",
//     "DarkBlue",
//     "DarkCyan",
//     "DarkGoldenRod",
//     "DarkGray",
//     "DarkGrey",
//     "DarkGreen",
//     "DarkKhaki",
//     "DarkMagenta",
//     "DarkOliveGreen",
//     "Darkorange",
//     "DarkOrchid",
//     "DarkRed",
//     "DarkSalmon",
//     "DarkSeaGreen",
//     "DarkSlateBlue",
//     "DarkSlateGray",
//     "DarkSlateGrey",
//     "DarkTurquoise",
//     "DarkViolet",
//     "DeepPink",
//     "DeepSkyBlue",
//     "DimGray",
//     "DimGrey",
//     "DodgerBlue",
//     "FireBrick",
//     "FloralWhite",
//     "ForestGreen",
//     "Fuchsia",
//     "Gainsboro",
//     "GhostWhite",
//     "Gold",
//     "GoldenRod",
//     "Gray",
//     "Grey",
//     "Green",
//     "GreenYellow",
//     "HoneyDew",
//     "HotPink",
//     "IndianRed",
//     "Indigo",
//     "Ivory",
//     "Khaki",
//     "Lavender",
//     "LavenderBlush",
//     "LawnGreen",
//     "LemonChiffon",
//     "LightBlue",
//     "LightCoral",
//     "LightCyan",
//     "LightGoldenRodYellow",
//     "LightGray",
//     "LightGrey",
//     "LightGreen",
//     "LightPink",
//     "LightSalmon",
//     "LightSeaGreen",
//     "LightSkyBlue",
//     "LightSlateGray",
//     "LightSlateGrey",
//     "LightSteelBlue",
//     "LightYellow",
//     "Lime",
//     "LimeGreen",
//     "Linen",
//     "Magenta",
//     "Maroon",
//     "MediumAquaMarine",
//     "MediumBlue",
//     "MediumOrchid",
//     "MediumPurple",
//     "MediumSeaGreen",
//     "MediumSlateBlue",
//     "MediumSpringGreen",
//     "MediumTurquoise",
//     "MediumVioletRed",
//     "MidnightBlue",
//     "MintCream",
//     "MistyRose",
//     "Moccasin",
//     "NavajoWhite",
//     "Navy",
//     "OldLace",
//     "Olive",
//     "OliveDrab",
//     "Orange",
//     "OrangeRed",
//     "Orchid",
//     "PaleGoldenRod",
//     "PaleGreen",
//     "PaleTurquoise",
//     "PaleVioletRed",
//     "PapayaWhip",
//     "PeachPuff",
//     "Peru",
//     "Pink",
//     "Plum",
//     "PowderBlue",
//     "Purple",
//     "Red",
//     "RosyBrown",
//     "RoyalBlue",
//     "SaddleBrown",
//     "Salmon",
//     "SandyBrown",
//     "SeaGreen",
//     "SeaShell",
//     "Sienna",
//     "Silver",
//     "SkyBlue",
//     "SlateBlue",
//     "SlateGray",
//     "SlateGrey",
//     "Snow",
//     "SpringGreen",
//     "SteelBlue",
//     "Tan",
//     "Teal",
//     "Thistle",
//     "Tomato",
//     "Turquoise",
//     "Violet",
//     "Wheat",
//     "White",
//     "WhiteSmoke",
//     "Yellow",
//     "YellowGreen"
// ];

var colorNames = [
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgrey",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "grey",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgrey",
    "lightgreen",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen"
];

export default colorNames;